obj-$(CONFIG_MACH_M8) += htc_m8-panel.o
obj-$(CONFIG_MACH_EYE_UL) += htc_eye-panel.o
obj-$(CONFIG_MACH_MEC_WHL) += htc_m8-panel.o
obj-$(CONFIG_MACH_B2_WLJ) += htc_b2-panel.o
obj-$(CONFIG_MACH_B2_UL) += htc_b2-panel.o
